x-common-settings: &common-settings
  restart: always
  build:
    context: .
  networks:
    - db_network
    - minio_network
    - meilisearch_network
    - traefik

services:
  foxochat-backend:
    <<: *common-settings
    container_name: foxochat-backend
    image: foxochat/backend:prod
    labels:
      traefik.enable: true
      traefik.http.routers.foxochat-backend.rule: Host(`api.foxochat.app`)
      traefik.http.services.foxochat-backend.loadbalancer.server.port: 8080
      traefik.http.routers.foxochat-backend.middlewares: ratelimit@file

  foxochat-backend-dev:
    <<: *common-settings
    container_name: foxochat-backend-dev
    image: foxochat/backend:dev
    labels:
      traefik.enable: true
      traefik.http.routers.foxochat-backend-dev.rule: Host(`api-dev.foxochat.app`)
      traefik.http.services.foxochat-backend-dev.loadbalancer.server.port: 8080
      traefik.http.routers.foxochat-backend-dev.middlewares: ratelimit@file

networks:
  db_network:
    external: true
  minio_network:
    external: true
  meilisearch_network:
    external: true
  traefik:
    external: true
