spring:
  threads:
    virtual:
      enabled: true
  jmx:
    enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    username: foxochat
    password: passwd
    url: jdbc:postgresql://localhost:5432/foxochat
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: true
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  jackson:
    property-naming-strategy: SNAKE_CASE

logging:
  level:
    root: INFO
    org.springframework: INFO
    app.foxochat: INFO

springdoc:
  swagger-ui:
    enabled: false

smtp:
  host: smtp.mailersend.net
  port: 587
  username: user
  password: pass
  email: noreply@foxochat.app

minio:
  url: https://min.io # minio api url
  name: # access key
  secret: # secret key

meili:
  master_key: # meilisearch master key

jwt:
  secret: # random secret key

api:
  version: 1
  env: dev # dev or prod
  url: http://localhost:8080
  cdn:
    url: https://media.foxochat.app
  gateway:
    production_url: wss://api.foxochat.app
    development_url: wss://api-dev.foxochat.app
  app:
    production_url: https://api.foxochat.app
    development_url: https://api-dev.foxochat.app
