name: Deploy Backend

permissions:
  contents: read

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: cloud
    environment: ${{ github.ref_name == 'main' && 'production' || github.ref_name == 'dev' && 'development' || 'development' }}
    steps:
      - uses: actions/checkout@v4

      - name: Create config
        run: |
          cat <<EOF > src/main/resources/application.properties
          spring.threads.virtual.enabled=true
          spring.jmx.enabled=false
          spring.datasource.driver-class-name=org.postgresql.Driver
          spring.datasource.username=${{ secrets.DB_USERNAME }}
          spring.datasource.password=${{ secrets.DB_PASSWORD }}
          spring.datasource.url=jdbc:postgresql://${{ secrets.DB_HOSTNAME }}:${{ secrets.DB_PORT }}/${{ secrets.DB_DATABASE }}
          spring.jpa.hibernate.ddl-auto=none
          spring.jpa.open-in-view=true
          spring.data.jpa.repositories.bootstrap-mode: deferred
          logging.level.root=${{ vars.ENV == 'dev' && 'INFO' || 'WARN' }}
          logging.level.org.springframework=${{ vars.ENV == 'dev' && 'INFO' || 'WARN' }}
          logging.level.app.foxochat=${{ vars.ENV == 'dev' && 'DEBUG' || 'WARN' }}
          spring.jackson.property-naming-strategy=SNAKE_CASE
          springdoc.swagger-ui.enabled=false
          smtp.host=${{ secrets.SMTP_HOSTNAME }}
          smtp.port=${{ secrets.SMTP_PORT }}
          smtp.username=${{ secrets.SMTP_USERNAME }}
          smtp.password=${{ secrets.SMTP_PASSWORD }}
          smtp.email=${{ secrets.SMTP_EMAIL }}
          jwt.secret=${{ secrets.JWT_SECRET }}
          minio.url=${{ vars.MINIO_URL }}
          minio.name=${{ secrets.MINIO_NAME }}
          minio.secret=${{ secrets.MINIO_SECRET }}
          meili.master_key=${{ secrets.MEILI_MASTER_KEY }}
          api.version=1
          api.env=${{ vars.ENV }}
          api.url=${{ vars.ENV == 'dev' && 'https://api-dev.foxochat.app' || 'https://api.foxochat.app' }}
          api.cdn.url=https://media.foxochat.app
          api.gateway.production_url=wss://api.foxochat.app
          api.gateway.development_url=wss://api-dev.foxochat.app
          api.app.production_url=https://app.foxochat.app
          api.app.development_url=https://app-dev.foxochat.app
          EOF

      - name: Build
        env:
          JAVA_HOME: ${{ vars.JAVA_HOME }}
        run: |
          export PATH="${{ vars.JAVA_HOME }}/bin:$PATH"
          ./gradlew build

      - name: Run
        env:
          SUFFIX: ${{ vars.ENV == 'dev' && '-dev' || '' }}
        run: docker compose up foxochat-backend$SUFFIX -d --build

      - name: Trigger docs build
        run: curl -d "" "${{ secrets.DOCS_DEPLOY_HOOK_URL }}"
